### PR TITLE
Messaging app & follow-up email

### PR DESCRIPTION
**Pull request by yakkomajuri**
Bringing back the reverted PR #20 

I might not have time today to fully fix this but at least will leave this here.

### CODE REVIEW

**Comment by yakkomajuri** [comment]
@paolodamico

**Comment by paolodamico** [comment]
Thanks for the prompt action @yakkomajuri, I'll investigate and merge it back with the fix.

**Comment by Twixes** [comment]
Not sure how to do migrations in `messaging`.

**Comment by paolodamico** [comment]
> Not sure how to make migrations in `messaging`.

I can help with that, I'll make some adjustments too and tag you.

**Comment by paolodamico** [comment]
When we add more emails we can abstract the code on tasks.py (fetching the user record, locking the UserMessagingRecord and sending the event via `posthoganalytics`) to a decorator.

**Review by Twixes — APPROVED** [review]

**Pull request merged**
