### PR TITLE
Custom plan/pricing support

### PR DESCRIPTION
**Pull request by paolodamico**
Extends https://github.com/posthog/posthog/pull/1535 to support custom plan/pricing on signup.

- Introduces the `Plan` model to manage dynamic plans on the platform. Each plan has its own Stripe `price_id`.
- Supports passing an additional `plan` attribute on the API signup request to automatically set up a particular `TeamBilling` for the newly created team.

N.B. When deploying this remember to update the environment variables appropriately, and migrate `cus_***Fka4` (156) to new Stripe account.

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Small nitpick and unrelated to the PR but I think I'd prefer a green checkmark for when billing is successful

**Comment by paolodamico** [comment]
> Small nitpick and unrelated to the PR but I think I'd prefer a green checkmark for when billing is successful

Which checkmark are you referring to? On /billing/success?

**Comment by paolodamico** [comment]
> Small nitpick and unrelated to the PR but I think I'd prefer a green checkmark for when billing is successful

Agreed, feel free to change, those views were made pretty quickly to support billing. I'll also be working on some designs for all the billing stuff soon if you prefer to wait until then.

**Review by yakkomajuri — APPROVED** [review]
Made some minor changes but otherwise looks good!

**Pull request merged**
